/*
    10. 
    Utilizando dos clases, al menos, realice una calculadora con las 
    operaciones básicas, sumar, restar, multiplicar y dividir, cuidar 
    la división entre cero. Validar que la entrada sean solamente números. 
    
    Este programa deberá de tener una interfaz gráfica.
 */
package actividades;
import java.util.Arrays;
/**
 *
 * @author franciscobecerra
 */
public class Actividad10 extends javax.swing.JFrame {
    
    static String operation = null;
    static int n = 0;

    public Actividad10() {
        initComponents();
        autor(10,"Calculadora");
    }
    
    public static void autor( int num, String name ){
        System.out.println("\nActividad #"+num+": "+name+"\n");
        
        System.out.println("programa elaborado por francisco becerra para la materia");
        System.out.println("de Programacion en los cursos propedeuticos de posgrado ");
        System.out.println("en ciencias computacionales\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        sum = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        mul = new javax.swing.JButton();
        div = new javax.swing.JButton();
        c = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        equals = new javax.swing.JButton();
        num9 = new javax.swing.JButton();

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("jButton1");
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sum.setBackground(new java.awt.Color(255, 153, 0));
        sum.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        sum.setForeground(new java.awt.Color(0, 0, 0));
        sum.setText("+");
        sum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumMouseClicked(evt);
            }
        });
        jPanel2.add(sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 53));

        sub.setBackground(new java.awt.Color(255, 153, 0));
        sub.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        sub.setForeground(new java.awt.Color(0, 0, 0));
        sub.setText("−");
        sub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subMouseClicked(evt);
            }
        });
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        jPanel2.add(sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, 53));

        mul.setBackground(new java.awt.Color(255, 153, 0));
        mul.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        mul.setForeground(new java.awt.Color(0, 0, 0));
        mul.setText("×");
        mul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mulMouseClicked(evt);
            }
        });
        jPanel2.add(mul, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 50, 53));

        div.setBackground(new java.awt.Color(255, 153, 0));
        div.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        div.setForeground(new java.awt.Color(0, 0, 0));
        div.setText("÷");
        div.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divMouseClicked(evt);
            }
        });
        jPanel2.add(div, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 53));

        c.setBackground(new java.awt.Color(255, 153, 0));
        c.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        c.setForeground(new java.awt.Color(0, 0, 0));
        c.setText("C");
        c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cMouseClicked(evt);
            }
        });
        jPanel2.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 253, 50, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 70, 320));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(60, 63, 65));

        label.setBackground(new java.awt.Color(51, 51, 51));
        label.setFont(new java.awt.Font(".SF NS Text", 0, 36)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 60));

        num1.setBackground(new java.awt.Color(102, 102, 102));
        num1.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        num1.setLabel("1");
        num1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num1MouseClicked(evt);
            }
        });
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        jPanel4.add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, 50));

        num2.setBackground(new java.awt.Color(102, 102, 102));
        num2.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        num2.setText("2");
        num2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num2MouseClicked(evt);
            }
        });
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        jPanel4.add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 70, 50));

        num3.setBackground(new java.awt.Color(102, 102, 102));
        num3.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        num3.setText("3");
        num3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num3MouseClicked(evt);
            }
        });
        jPanel4.add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 70, 50));

        num4.setBackground(new java.awt.Color(102, 102, 102));
        num4.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        num4.setText("4");
        num4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num4MouseClicked(evt);
            }
        });
        jPanel4.add(num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 70, 50));

        num5.setBackground(new java.awt.Color(102, 102, 102));
        num5.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        num5.setText("5");
        num5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num5MouseClicked(evt);
            }
        });
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });
        jPanel4.add(num5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 70, 50));

        num6.setBackground(new java.awt.Color(102, 102, 102));
        num6.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        num6.setText("6");
        num6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num6MouseClicked(evt);
            }
        });
        jPanel4.add(num6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 70, 50));

        num7.setBackground(new java.awt.Color(102, 102, 102));
        num7.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        num7.setText("7");
        num7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num7MouseClicked(evt);
            }
        });
        jPanel4.add(num7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 50));

        num8.setBackground(new java.awt.Color(102, 102, 102));
        num8.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        num8.setText("8");
        num8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num8MouseClicked(evt);
            }
        });
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });
        jPanel4.add(num8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 70, 50));

        num0.setBackground(new java.awt.Color(102, 102, 102));
        num0.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        num0.setText("0");
        num0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num0MouseClicked(evt);
            }
        });
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });
        jPanel4.add(num0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 70, 50));

        equals.setBackground(new java.awt.Color(51, 51, 51));
        equals.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        equals.setText("=");
        equals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equalsMouseClicked(evt);
            }
        });
        equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsActionPerformed(evt);
            }
        });
        jPanel4.add(equals, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 150, 50));

        num9.setBackground(new java.awt.Color(102, 102, 102));
        num9.setFont(new java.awt.Font(".SF NS Text", 0, 24)); // NOI18N
        num9.setText("9");
        num9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num9MouseClicked(evt);
            }
        });
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });
        jPanel4.add(num9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 70, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num2ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num5ActionPerformed

    private void equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equalsActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num0ActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num8ActionPerformed

    private void num1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num1MouseClicked
        if( operation == "CLEAR" ){
            label.setText("1");
            operation = null;
        }else if( label.getText() == "0" ){
            label.setText("1");
        }else{
            label.setText( label.getText() + "1" );
        }
    }//GEN-LAST:event_num1MouseClicked

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num1ActionPerformed

    private void num2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num2MouseClicked
        if( operation == "CLEAR" ){
            label.setText("2");
            operation = null;
        }else if( label.getText() == "0" ){
            label.setText("2");
        }else{
            label.setText( label.getText() + "2" );
        }
    }//GEN-LAST:event_num2MouseClicked

    private void num3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num3MouseClicked
        if( operation == "CLEAR" ){
            label.setText("3");
            operation = null;
        }else if( label.getText() == "0" ){
            label.setText("3");
        }else{
            label.setText( label.getText() + "3" );
        }
    }//GEN-LAST:event_num3MouseClicked

    private void num4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num4MouseClicked
        if( operation == "CLEAR" ){
            label.setText("4");
            operation = null;
        }else if( label.getText() == "0" ){
            label.setText("4");
        }else{
            label.setText( label.getText() + "4" );
        }
    }//GEN-LAST:event_num4MouseClicked

    private void num5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num5MouseClicked
        if( operation == "CLEAR" ){
            label.setText("5");
            operation = null;
        }else if( label.getText() == "0" ){
            label.setText("5");
        }else{
            label.setText( label.getText() + "5" );
        }
    }//GEN-LAST:event_num5MouseClicked

    private void num6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num6MouseClicked
        if( operation == "CLEAR" ){
            label.setText("6");
            operation = null;
        }else if( label.getText() == "0" ){
            label.setText("6");
        }else{
            label.setText( label.getText() + "6" );
        }
    }//GEN-LAST:event_num6MouseClicked

    private void num7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num7MouseClicked
        if( operation == "CLEAR" ){
            label.setText("7");
            operation = null;
        }else if( label.getText() == "0" ){
            label.setText("7");
        }else{
            label.setText( label.getText() + "7" );
        }
    }//GEN-LAST:event_num7MouseClicked

    private void num8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num8MouseClicked
        if( operation == "CLEAR" ){
            label.setText("8");
            operation = null;
        }else if( label.getText() == "0" ){
            label.setText("8");
        }else{
            label.setText( label.getText() + "8" );
        }
    }//GEN-LAST:event_num8MouseClicked

    private void num0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num0MouseClicked
        if( operation == "CLEAR" ){
            label.setText("0");
            operation = null;
        }else if( label.getText() == "0" ){
            label.setText("0");
        }else{
            label.setText( label.getText() + "0" );
        }
    }//GEN-LAST:event_num0MouseClicked

    private void sumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumMouseClicked
        operation = "sum";
        n = Integer.parseInt(label.getText());
        label.setText("0");
    }//GEN-LAST:event_sumMouseClicked

    private void subMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subMouseClicked
        operation = "sub";
        n = Integer.parseInt(label.getText());
        label.setText("0");
    }//GEN-LAST:event_subMouseClicked

    private void mulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mulMouseClicked
        operation = "mul";
        n = Integer.parseInt(label.getText());
        label.setText("0");
    }//GEN-LAST:event_mulMouseClicked

    private void divMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divMouseClicked
        operation = "div";
        n = Integer.parseInt(label.getText());
        label.setText("0");
    }//GEN-LAST:event_divMouseClicked

    private void cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseClicked
        operation = null;
        n = 0;
        label.setText("0");
    }//GEN-LAST:event_cMouseClicked

    private void equalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalsMouseClicked
        String res = make_operation( n, Integer.parseInt(label.getText()), operation );
        
        try{
            String[] parts = res.split("[.]");

            if( parts[1].equals("0") ){ 
                label.setText( parts[0] );
            }else{ 
                label.setText( res ); 
            }
            
        }catch( Exception e ){
            label.setText( "Error" ); 
        }
        operation = "CLEAR";
        n = 0;
    }//GEN-LAST:event_equalsMouseClicked

    private void num9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num9MouseClicked
        if( operation == "CLEAR" ){
            label.setText("9");
            operation = null;
        }else if( label.getText() == "0" ){
            label.setText("9");
        }else{
            label.setText( label.getText() + "9" );
        }
    }//GEN-LAST:event_num9MouseClicked

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num9ActionPerformed

    private String make_operation( int n1, int n2, String operation ){
        double res = 0;
        
//        System.out.println( n1 );
//        System.out.println( operation );
//        System.out.println( n2 );
        
        try{
            switch(operation){
                case "sum": {
                    res = (double) n1 + n2;
                    break;
                }
                case "sub": {
                    res = (double) n1 - n2;
                    break;
                }
                case "mul": {
                    res = (double) n1 * n2;
                    break;
                }
                case "div": {
                    res = (double) n1 / n2;
                    break;
                } 
                default : { res = 0; }
            }
            return Double.toString(res);
        }catch(Exception e){
            operation = "CLEAR";
            return "Error";
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actividad10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actividad10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actividad10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actividad10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actividad10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c;
    private javax.swing.JButton div;
    private javax.swing.JButton equals;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel label;
    private javax.swing.JButton mul;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton sub;
    private javax.swing.JButton sum;
    // End of variables declaration//GEN-END:variables
}
